### ISSUE TITLE
running core code generator error

### ISSUE THREAD

**Issue by AnaBit** [COVESA/capicxx-core-tools#17]
!SESSION 2019-06-11 10:11:48.630 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_212
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.equinox.launcher.win32.win32.x86 2 0 2019-06-11 10:11:48.902
!MESSAGE Could not resolve module: org.eclipse.equinox.launcher.win32.win32.x86 [34]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=win32) (osgi.os=win32) (osgi.arch=x86))"

!ENTRY org.eclipse.osgi 4 0 2019-06-11 10:11:48.902
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.genivi.commonapi.console.application" could not be found in the registry. The applications available are: org.eclipse.emf.codegen.CodeGen, org.eclipse.emf.codegen.JMerger, org.eclipse.emf.codegen.ecore.Generator, org.eclipse.emf.mwe.core.WorkflowRunner, org.eclipse.equinox.app.error, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer.
        at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
        at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by gunnarx** [comment]
Which version of the code generator?  Did you compile it?  Or download it?

**Comment by gunnarx** [comment]
@AnaBit Is this still an open question?

**Comment by AnaBit** [comment]
I downloaded it from here:
https://github.com/GENIVI/capicxx-core-tools/releases/download/3.1.12.3/commonapi-generator.zip  
version:
3.1.12.3

**Comment by cogle** [comment]
I am also having the same problem was there ever any solution or update to this issue ?

**Comment by mishaboyko** [comment]
Use newer version:
wget https://github.com/GENIVI/capicxx-someip-tools/releases/download/3.1.12.2/commonapi_someip_generator.zip

**Comment by MFait** [comment]
I get the same issue using 
commonapi_generator 3.1.12.3
commonapi_someip_generator 3.1.12.2

**Comment by mishaboyko** [comment]
@MFait: 
Did you install/switch your Java SDK to openjdk-8-jdk:
`sudo update-alternatives --config java`  ?

**Comment by rlokanathan** [comment]
I also having the same issue in Windows. When I try to use the commonapi-generator, it shows the same error:

`!SESSION 2020-08-12 09:30:48.751 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_261
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -sk fidl\HelloWorld.fidl
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -sk fidl\HelloWorld.fidl

!ENTRY org.eclipse.equinox.launcher.win32.win32.x86 2 0 2020-08-12 09:30:49.718
!MESSAGE Could not resolve module: org.eclipse.equinox.launcher.win32.win32.x86 [34]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=win32) (osgi.os=win32) (osgi.arch=x86))"


!ENTRY org.eclipse.osgi 4 0 2020-08-12 09:30:49.720
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.genivi.commonapi.console.application" could not be found in the registry. The applications available are: org.eclipse.emf.codegen.CodeGen, org.eclipse.emf.codegen.JMerger, org.eclipse.emf.codegen.ecore.Generator, org.eclipse.emf.mwe.core.WorkflowRunner, org.eclipse.equinox.app.error, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
`

I can see for Linux is rather straightforward just by installing java sdk 8 could fixed the problem. But in windows even though I am using Java sdk 8 still its the same issue. I am using the latest commonapi-generator (3.1.12.4)

**Comment by goncaloalmeida** [comment]
This problem is still occurring?
