### ISSUE TITLE
Application "org.genivi.commonapi.console.application" could not be found in the registry

### ISSUE THREAD

**Issue by rlokanathan** [COVESA/capicxx-core-tools#24]
Hi,

This is the first time I am using common API in windows. I already have my franca file. Now I tried to use the commonapi-generator-windows-x86_64.exe to generate the common API codes. But it seems like the generator is not generating the common API codes. 

Here is the error from the log.

!SESSION 2020-08-12 09:30:48.751 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_261
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -sk fidl\HelloWorld.fidl
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -sk fidl\HelloWorld.fidl

!ENTRY org.eclipse.equinox.launcher.win32.win32.x86 2 0 2020-08-12 09:30:49.718
!MESSAGE Could not resolve module: org.eclipse.equinox.launcher.win32.win32.x86 [34]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=win32) (osgi.os=win32) (osgi.arch=x86))"

!ENTRY org.eclipse.osgi 4 0 2020-08-12 09:30:49.720
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.genivi.commonapi.console.application" could not be found in the registry. The applications available are: org.eclipse.emf.codegen.CodeGen, org.eclipse.emf.codegen.JMerger, org.eclipse.emf.codegen.ecore.Generator, org.eclipse.emf.mwe.core.WorkflowRunner, org.eclipse.equinox.app.error, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

Previously, it shows error related to the java sdk. Because in my system I was using the java sdk 12. So for that issue, I have already installed and verified the java sdk 8. And maven is also installed in my windows PC. I am not sure what else could be missing to generate the common API codes.

Currently, this is the command I execute in my Windows command prompt:

`commonapi-generator\commonapi-generator-windows-x86_64.exe -sk fidl\HelloWorld.fidl`

**Comment by Fighter19** [comment]
Try to reinstall the commonapi-generator folder.
To me it seems like using the old folder than has accidentally been used with another JDK version, will not work afterwards.

Re-extract the ZIP file and try again, it helped for me.
I think the project gets badly configured with a newer JDK version.

**Comment by Gustavo1515** [comment]
Can you check if this issue was fixed on the last version?

Cc: @goncaloalmeida
