### ISSUE TITLE
can build  capicxx-core-tools successfully but can not run it successfully

### ISSUE THREAD

**Issue by hezhiye** [COVESA/capicxx-core-tools#43]
HI:
   i can build  capicxx-core-tools successfully using java8 but can not run.
   It seems that the jar conflict and the java program can not startup.

when i compile, i got 
+- (p2.eclipse-plugin:com.google.guava:jar:30.1.0.v20210127-2300:system - omitted for conflict with 18.0.0.v20161115-1643)
 (p2.eclipse-plugin:org.apache.log4j:jar:1.2.15.v201012070815:system - omitted for conflict with 1.2.19.v20220208-1728)

**Comment by hezhiye** [comment]
java.lang.RuntimeException: Application "org.genivi.commonapi.console.application" could not be found in the registry. The applications available are: org.eclipse.emf.codegen.CodeGen, org.eclipse.emf.codegen.JMerger, org.eclipse.emf.codegen.ecore.Generator, org.eclipse.emf.mwe.core.WorkflowRunner, org.eclipse.equinox.app.error, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer.
        at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:251)
        at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:32)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

**Comment by Gustavo1515** [comment]
Can you check if this issue was fixed on the last version?

Cc: @goncaloalmeida
