### ISSUE TITLE
Linux x86 binary shipped with 3.2.14 does not work

### ISSUE THREAD

**Issue by farcas-snps** [COVESA/capicxx-core-tools#75]
https://github.com/COVESA/capicxx-someip-tools/releases/download/3.2.14/commonapi_someip_generator.zip
commonapi-generator-linux-x86

```
!SESSION 2024-10-01 11:11:18.818 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_421
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86, WS=gtk, NL=en_US
Framework arguments:  -sk fidl/Attributes.fidl
Command-line arguments:  -os linux -ws gtk -arch x86 -sk fidl/Attributes.fidl

!ENTRY org.eclipse.equinox.launcher.win32.win32.x86 2 0 2024-10-01 11:11:19.102
!MESSAGE Could not resolve module: org.eclipse.equinox.launcher.win32.win32.x86 [34]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=win32) (osgi.os=win32) (osgi.arch=x86))"

!ENTRY org.eclipse.osgi 4 0 2024-10-01 11:11:19.102
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.genivi.commonapi.console.application" could not be found in the registry. The applications available are: org.eclipse.emf.codegen.CodeGen, org.eclipse.emf.codegen.JMerger, org.eclipse.emf.codegen.ecore.Generator, org.eclipse.emf.mwe.core.WorkflowRunner, org.eclipse.equinox.app.error, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:248)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:29)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```
With 3.2.0.1 it works.

**Comment by duartenfonseca** [comment]
We tried to reproduce the error in the following conditions:
- Files used: 
 https://github.com/COVESA/capicxx-core-tools/blob/master/CommonAPI-Examples/E02Attributes/fidl/E02Attributes.fidl
 https://github.com/COVESA/capicxx-core-tools/blob/master/CommonAPI-Examples/E02Attributes/fidl/E02Attributes-SomeIP.fdepl
- Java version: 1.8.0_421
- Commands used:
$ ./commonapi_someip_generator/commonapi-someip-generator-linux-x86_64 -d src-gen/someip ./fidl/E02Attributes-SomeIP.fdepl  
             $ ./commonapi_core_generator/commonapi-core-generator-linux-x86_64 -d src-gen/core -sk ./fidl/E02Attributes.fidl 
 
 
**In Linux x64 environment:** 
Executables used: core and someip from releases 3.2.14 and 3.2.0.1.
Result: core and someip files were generated correctly without errors.
 
**In Windows x86 virtual environment:** 
Executables used: core and someip from releases 3.2.14 and 3.2.0.1.
Result: core and someip files were generated correctly without errors.

**In Linux x86 virtual environment:** 
Executables used: core and someip from releases 3.2.14 and 3.2.0.1.
Eclipse version: 4.9.0
 
The following logs were obtained in the .metadata folder of the eclipse-workspace, with the core and someip files generated correctly: 
 
![image](https://github.com/user-attachments/assets/a6b0b279-f086-40fc-8c98-397c2ac1e923)

 
**Conclusion:**
It was not possible to reproduce the error. Please try to use a most recent version of executables (3.2.15) and let us know if you still have the same error. In that case please specify the conditions used to get the error.
